repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: fix-byte-order-marker # Strips BOM characters
          - id: trailing-whitespace # Trim any trailing whitespace from lines
          - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline
          - id: check-merge-conflict # Check for files that contain merge conflict strings
          - id: check-json # JSON Syntax Check
          - id: check-yaml # YAML Syntax Check

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.13
      hooks:
          - id: remove-crlf # Remove windows line endings

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.2.1
      hooks:
          - id: prettier # Formatter for JavaScript

    - repo: local
      hooks:
          - id: only-acceptible-filenames
            name: Only acceptible filenames
            entry: Filenames must be lower-case alphanumeric with only underscores, hyphens, and full-stops/periods
            language: fail
            files: "[^0-9a-z_\\-\\./]"
