export default {
    photosTab: '[aria-controls="photos"]',
    uncategorizedPhotosCount: '[class="category-item is-uncategorized active"] div',
    deleteButton: "#deleteBtn",
    photoSelectOption: '[class="photos-select"]',
    downloadButton: '[class="photos-download-button"]',
    superBlocksTab: '[aria-controls="availability"]',
    addNewSuperBlockButton: '[id="super-blocks"] [class="btn btn-primary"]',
    startDateField: "#id_start_date",
    enddateField: "#id_end_date",
    notesTextField: "#id_notes",
    saveButton: '[value="Save"]',
    editButton: '[id="super-blocks"] [class="btn btn-info btn-xs btn-block"]',
    superBlockDeleteButton: '[name="delete"]',
    documentsTab: '[aria-controls="documents"]',
    photosButton: '(//span[@class="glyphicon glyphicon-camera"])[index]',
    selectImageButton: '(//*[@class="select-submit"])[1]',
    returnButton: '//button[text()="Return"]',
    fileStatusDropdown: '[id="id_file_status"]',
    propertyCalendarTab: '[aria-controls="calendar"]',
    addByoBookingButton: '(//a[text()[normalize-space()="Add BYO Booking"]])[1]',
    faqButton: '//a[normalize-space(text())="Edit"]',
    property: '//a[normalize-space(text())="0E2E Test Property"]',
    textAreaLabel: '//label[contains(text(),"name")]',
    bold: '[title="Strong (Ctrl + B)"]',
    italic: '[title="Emphasis (Ctrl + I)"]',
    hyperlink: '[title="Link"]',
    url: '[name="url"]',
    textField: '[name="text"]',
    confirmButton: '[type="submit"]',
    insertlinkModelBox: '[class="trumbowyg-modal-box"]',
    saveButton: '[value="Save"]',
    updatedDescription: '//b[text()="label"]/..//following-sibling::td//p',
};
